-- ============================================================================
-- CORREÇÃO DO SCHEMA DA TABELA ENTREVISTAS - EDUCAFRO 2026
-- ============================================================================
-- Este script corrige os tipos ENUM problemáticos transformando-os em TEXT
-- e remove restrições NOT NULL para permitir campos vazios
-- ============================================================================

-- IMPORTANTE: Execute este script no SQL Editor do Supabase

-- Primeiro, vamos remover a tabela existente e recriá-la do zero
-- (isso é seguro em desenvolvimento, mas CUIDADO em produção!)

DROP TABLE IF EXISTS entrevistas CASCADE;

-- Criar a tabela do zero com tipos TEXT (mais flexível)
CREATE TABLE entrevistas (
    -- Campos automáticos
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),

    -- SEÇÃO 1: IDENTIFICAÇÃO
    entrevistador text,
    data_entrevista date,

    -- SEÇÃO 2: DADOS PESSOAIS
    nome_social text NOT NULL,
    nome_social_diferente text,
    nome_civil_completo text,
    telefone text,
    email text,
    data_nascimento date,
    cpf text,
    rg text,
    cidade text,
    naturalidade text,
    endereco text,
    bairro text,
    estado_civil text,

    -- SEÇÃO 3: RAÇA E COR
    raca_cor text,

    -- SEÇÃO 4: GÊNERO E ORIENTAÇÃO
    genero text,
    trans_travesti text,
    orientacao_sexual text,
    orientacao_sexual_outra text,

    -- SEÇÃO 5: ESCOLARIDADE E FAMÍLIA
    escolaridade text,
    escolaridade_curso text,
    escola_publica_privada text,
    nome_mae text,
    profissao_mae text,
    escolaridade_mae text,
    nome_pai text,
    profissao_pai text,
    escolaridade_pai text,

    -- SEÇÃO 6: VÍNCULO FAMILIAR
    familiar_nucleo text,
    vinculo_familiar text,
    nome_familiar text,

    -- SEÇÃO 7: MORADIA E INTERNET
    moradia_condicao text,
    moradia_tipo text,
    internet_tem text,
    internet_tipo text,
    internet_sinal text,

    -- SEÇÃO 8: TRABALHO E RENDA
    trabalho_renda_semana text,
    trabalho_ajuda_familiar text,
    trabalho_vinculo text,
    trabalho_horario_inicio text,
    trabalho_horario_fim text,
    trabalho_uso_dinheiro text,

    -- SEÇÃO 9: RENDA E BENEFÍCIOS
    renda_familiar text,
    beneficios_recebe text,
    beneficios_cadunico text,
    beneficios_tipo text[],
    cesta_basica text,

    -- SEÇÃO 10: FAMÍLIA E TRANSPORTE
    filhos_tem text,
    pensao_paga text,
    pensao_recebe text,
    transporte_veiculo text,
    transporte_meio text,
    transporte_auxilio text,

    -- SEÇÃO 11: SAÚDE
    saude_plano text,
    saude_servicos text[],
    saude_servicos_outro text,
    saude_tipo_sanguineo text,
    saude_psicoterapia text,
    saude_psicoterapia_outro text,
    saude_psicoterapia_tempo text,
    saude_psicoterapia_encerramento text,
    saude_deficiencia text,
    saude_deficiencia_qual text,
    saude_familiar_deficiencia text,
    saude_familia_deficiencia_qual text,
    saude_problemas text,
    saude_problemas_qual text,
    saude_alergias text,
    saude_alergias_qual text,
    saude_medicamentos text,
    saude_medicamentos_qual text,
    saude_substancias text,
    saude_substancias_qual text,

    -- SEÇÃO 12: COTIDIANO E OBJETIVOS
    cotidiano_mora_com text,
    cotidiano_mora_com_quem text,
    cotidiano_relacao text,
    cotidiano_historico text,
    objetivo_curso text,
    objetivo_expectativa text,
    objetivo_motivacao text,
    objetivo_temas text,
    objetivo_frequencia text,

    -- SEÇÃO 13: CONSENTIMENTO LGPD
    lgpd_consentimento boolean DEFAULT false
);

-- ============================================================================
-- COMENTÁRIOS NAS COLUNAS (DOCUMENTAÇÃO)
-- ============================================================================

COMMENT ON TABLE entrevistas IS 'Tabela de entrevistas sociais Educafro 2026';
COMMENT ON COLUMN entrevistas.id IS 'ID único da entrevista';
COMMENT ON COLUMN entrevistas.created_at IS 'Data de criação do registro';
COMMENT ON COLUMN entrevistas.updated_at IS 'Data da última atualização';
COMMENT ON COLUMN entrevistas.nome_social IS 'Nome completo ou social (nome de uso cotidiano)';
COMMENT ON COLUMN entrevistas.nome_social_diferente IS 'Se o nome social é diferente do nome civil (Sim/Não/Prefiro não responder)';
COMMENT ON COLUMN entrevistas.nome_civil_completo IS 'Nome civil completo (opcional, para uso administrativo futuro)';
COMMENT ON COLUMN entrevistas.data_nascimento IS 'Data de nascimento do entrevistado';
COMMENT ON COLUMN entrevistas.raca_cor IS 'Raça/Cor autodeclarada';
COMMENT ON COLUMN entrevistas.genero IS 'Identidade de gênero';
COMMENT ON COLUMN entrevistas.trans_travesti IS 'Se a pessoa é trans ou travesti';
COMMENT ON COLUMN entrevistas.orientacao_sexual IS 'Orientação sexual';
COMMENT ON COLUMN entrevistas.saude_servicos IS 'Array com os serviços de saúde utilizados';
COMMENT ON COLUMN entrevistas.beneficios_tipo IS 'Array com os tipos de benefícios recebidos';
COMMENT ON COLUMN entrevistas.lgpd_consentimento IS 'Consentimento para uso dos dados conforme LGPD';

-- ============================================================================
-- ÍNDICES PARA MELHOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_entrevistas_created_at ON entrevistas(created_at);
CREATE INDEX IF NOT EXISTS idx_entrevistas_data_entrevista ON entrevistas(data_entrevista);
CREATE INDEX IF NOT EXISTS idx_entrevistas_entrevistador ON entrevistas(entrevistador);
CREATE INDEX IF NOT EXISTS idx_entrevistas_cidade ON entrevistas(cidade);
CREATE INDEX IF NOT EXISTS idx_entrevistas_raca_cor ON entrevistas(raca_cor);
CREATE INDEX IF NOT EXISTS idx_entrevistas_genero ON entrevistas(genero);
CREATE INDEX IF NOT EXISTS idx_entrevistas_objetivo_curso ON entrevistas(objetivo_curso);

-- ============================================================================
-- FUNÇÃO PARA ATUALIZAR updated_at AUTOMATICAMENTE
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_entrevistas_updated_at 
    BEFORE UPDATE ON entrevistas 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- POLÍTICA RLS (Row Level Security) - PERMITIR INSERÇÃO E LEITURA
-- ============================================================================

-- Ativa RLS na tabela
ALTER TABLE entrevistas ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas se existirem
DROP POLICY IF EXISTS "Permitir inserção anônima" ON entrevistas;
DROP POLICY IF EXISTS "Permitir leitura anônima" ON entrevistas;
DROP POLICY IF EXISTS "Permitir atualização anônima" ON entrevistas;
DROP POLICY IF EXISTS "Permitir exclusão anônima" ON entrevistas;

-- Política para permitir INSERT (criar novas entrevistas)
CREATE POLICY "Permitir inserção anônima" ON entrevistas
FOR INSERT
TO anon
WITH CHECK (true);

-- Política para permitir SELECT (ler entrevistas)
CREATE POLICY "Permitir leitura anônima" ON entrevistas
FOR SELECT
TO anon
USING (true);

-- Política para permitir UPDATE (atualizar entrevistas)
CREATE POLICY "Permitir atualização anônima" ON entrevistas
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

-- Política para permitir DELETE (deletar entrevistas - apenas para testes)
CREATE POLICY "Permitir exclusão anônima" ON entrevistas
FOR DELETE
TO anon
USING (true);

-- ============================================================================
-- VERIFICAÇÃO FINAL
-- ============================================================================

-- Verifica a estrutura da tabela
SELECT 
    column_name, 
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'entrevistas'
ORDER BY ordinal_position;
