export const FIELD_LABELS = {
    // Identificação
    entrevistador: "Responsáveis pela Entrevista",
    entrevistador_outro: "Outro Responsável",
    data_entrevista: "Data da Entrevista",

    // Dados Pessoais
    nome_completo: "Nome Completo",
    nome_mesmo_documento: "Nome igual ao documento?",
    nome_civil_documento: "Nome Civil",
    email: "E-mail",
    telefone: "Telefone (WhatsApp)",
    data_nascimento: "Data de Nascimento",
    cpf: "CPF",
    rg: "RG",
    estado_civil: "Estado Civil",
    cidade: "Cidade",
    cidade_outra: "Outra Cidade",
    naturalidade: "Naturalidade",
    bairro: "Bairro",
    endereco: "Endereço",

    // Raça/Cor e Pronomes
    raca_cor: "Raça/Cor",
    pronomes: "Pronomes",

    // Gênero e Orientação
    genero: "Identidade de Gênero",
    genero_outro: "Outro Gênero",
    trans_travesti: "Trans ou Travesti?",
    orientacao_sexual: "Orientação Sexual",
    orientacao_sexual_outra: "Outra Orientação",

    // Escolaridade e Família
    escolaridade: "Escolaridade",
    escolaridade_outro: "Especifique Escolaridade",
    escola_publica_privada: "Escola Pública/Particular",
    nome_mae: "Nome da Mãe",
    profissao_mae: "Profissão da Mãe",
    escolaridade_mae: "Escolaridade da Mãe",
    escolaridade_mae_outro: "Especifique Escolaridade Mãe",
    nome_pai: "Nome do Pai",
    profissao_pai: "Profissão do Pai",
    escolaridade_pai: "Escolaridade do Pai",
    escolaridade_pai_outro: "Especifique Escolaridade Pai",

    // Vínculo Familiar
    familiar_nucleo: "Familiar na Educafro?",
    vinculo_familiar: "Vínculo Familiar",
    vinculo_familiar_outro: "Especifique Vínculo",
    nome_familiar: "Nome do Familiar",

    // Moradia e Internet
    moradia_condicao: "Condição da Moradia",
    moradia_condicao_outro: "Outra Condição Moradia",
    moradia_tipo: "Tipo de Construção",
    moradia_tipo_outro: "Outro Tipo Construção",
    internet_tem: "Possui Internet?",
    internet_tipo: "Tipo de Conexão",
    internet_tipo_outro: "Outro Tipo Conexão",
    internet_sinal: "Sinal Estável?",
    internet_sinal_outro: "Especifique Sinal",

    // Trabalho e Renda
    trabalho_renda_semana: "Teve renda semana passada?",
    trabalho_ajuda_familiar: "Ajudou familiar sem pagamento?",
    trabalho_vinculo: "Vínculo de Trabalho",
    trabalho_vinculo_outro: "Outro Vínculo Trabalho",
    trabalho_horario_inicio: "Horário Início Trabalho",
    trabalho_horario_fim: "Horário Fim Trabalho",
    trabalho_uso_dinheiro: "Principal uso do dinheiro",

    // Renda e Benefícios
    renda_familiar: "Faixa de Renda Familiar",
    renda_familiar_outro: "Outra Renda",
    beneficios_recebe: "Recebe Benefício Social?",
    beneficios_cadunico: "Possui CadÚnico?",
    beneficios_tipo: "Quais Benefícios?",
    beneficios_outro: "Outro Benefício",
    cesta_basica: "Necessita Cesta Básica?",

    // Filhos, Transporte e Saúde
    filhos_tem: "Possui Filhos?",
    pensao_paga: "Paga Pensão?",
    pensao_recebe: "Recebe Pensão?",
    transporte_veiculo: "Veículo Próprio",
    transporte_meio: "Como vai à Educafro",
    transporte_meio_outro: "Outro Meio Transporte",
    transporte_auxilio: "Necessita Auxílio Transporte?",
    saude_plano: "SUS ou Plano de Saúde?",
    saude_servicos: "Serviços do SUS utilizados",
    saude_servicos_outro: "Outro Serviço SUS",
    saude_tipo_sanguineo: "Tipo Sanguíneo",
    saude_psicoterapia: "Realiza Psicoterapia?",
    saude_psicoterapia_outro: "Especifique Psicoterapia",
    saude_psicoterapia_tempo: "Tempo de Psicoterapia",
    saude_psicoterapia_encerramento: "Tempo de Encerramento",
    saude_deficiencia: "Possui Deficiência?",
    saude_deficiencia_qual: "Qual Deficiência?",
    saude_familiar_deficiencia: "Familiar com Deficiência?",
    saude_familia_deficiencia_qual: "Qual Deficiência Familiar?",
    saude_problemas: "Problema de saúde?",
    saude_problemas_qual: "Qual Problema?",
    saude_alergias: "Possui Alergia?",
    saude_alergias_qual: "Qual Alergia?",
    saude_medicamentos: "Medicamento Contínuo?",
    saude_medicamentos_qual: "Qual Medicamento?",
    saude_substancias: "Usa Substância Psicoativa?",
    saude_substancias_qual: "Qual Substância?",

    // Cotidiano e Objetivo
    cotidiano_mora_com: "Mora sozinho?",
    cotidiano_mora_com_quem: "Com quem mora?",
    cotidiano_relacao: "Relação com a Família",
    cotidiano_historico: "Histórico Pessoal/Familiar",
    objetivo_curso: "Curso de Interesse",
    objetivo_expectativa: "Expectativa dos Responsáveis",
    objetivo_educafro: "Objetivo na Educafro",
    objetivo_educafro_outro: "Outro Objetivo",
    objetivo_temas: "Temas de Interesse",
    objetivo_frequencia: "Frequência Pretendida",
    objetivo_frequencia_outro: "Outra Frequência",

    // Metadados
    status_formulario: "Status do Formulário",
    created_at: "Data de Criação"
};

export const FIELD_ORDER = [
    'nome_completo',
    'status_formulario',
    'created_at',
    'entrevistador',
    'data_entrevista',
    'email',
    'telefone',
    'cpf',
    'rg',
    'data_nascimento',
    'estado_civil',
    'cidade',
    'bairro',
    'endereco',
    'raca_cor',
    'genero',
    'trans_travesti',
    'orientacao_sexual',
    'escolaridade',
    'escola_publica_privada',
    'nome_mae',
    'profissao_mae',
    'escolaridade_mae',
    'nome_pai',
    'profissao_pai',
    'escolaridade_pai',
    'familiar_nucleo',
    'vinculo_familiar',
    'nome_familiar',
    'moradia_condicao',
    'moradia_tipo',
    'internet_tem',
    'internet_tipo',
    'internet_sinal',
    'trabalho_renda_semana',
    'trabalho_ajuda_familiar',
    'trabalho_vinculo',
    'trabalho_horario_inicio',
    'trabalho_horario_fim',
    'trabalho_uso_dinheiro',
    'renda_familiar',
    'beneficios_recebe',
    'beneficios_cadunico',
    'beneficios_tipo',
    'cesta_basica',
    'filhos_tem',
    'pensao_paga',
    'pensao_recebe',
    'transporte_veiculo',
    'transporte_meio',
    'transporte_auxilio',
    'saude_plano',
    'saude_servicos',
    'saude_tipo_sanguineo',
    'saude_psicoterapia',
    'saude_deficiencia',
    'saude_problemas',
    'saude_alergias',
    'saude_medicamentos',
    'saude_substancias',
    'cotidiano_mora_com',
    'cotidiano_mora_com_quem',
    'cotidiano_relacao',
    'cotidiano_historico',
    'objetivo_curso',
    'objetivo_expectativa',
    'objetivo_educafro',
    'objetivo_temas',
    'objetivo_frequencia'
];
